<?php
$isSignedIn = false;
?>

<div id="wrapper">
        <?php if(isset($this->message)) :?>
            <div class="notification alert alert-danger">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <?php echo $this->message;?>
            </div>
        <?php endif;?>
    <div id="sidebar-wrapper">
        <div class="sidebar-nav nav" id="sidebar-nav">
            <ul id="sidebar-icons">
                <li>
                    <?php
                    if ($this->isSignedIn) {
                        echo "<a href='" . $this->baseUrl() . "/index/sign-out'>
                            <span class='fa fa-sign-out'></span></a>";
                    } else {
                        echo "<a href='#signIn' data-toggle='tab'>
                            <span class='menu-open fa fa-sign-in'></span></a>";
                    }
                    ?>
                </li>
                <li><a href="#signUp" data-toggle="tab"><span class="menu-open fa fa-user"></span></a></li>
                <li><a href="#" data-toggle="tab"><span class="fa fa-cogs"></span></a></li>
                <li><a href="#about" data-toggle="tab"><span class="menu-open fa fa-info-circle"></span></a></li>
                <li><a href="#" id="menu-close" data-toggle="tab"><span class="fa fa-close"></span></a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane" id="signIn">
                    <h3>Sign in</h3>
                    <div class="forms">
                        <?php
                        echo $this->signInForm;
                        ?>
                        <h4>Don't have an account?<br>Sign up by clicking the
                            <span class="menu-open fa fa-user"></span> on the sidebar.</h4>
                        <h4>Or Sign in with</h4>
                        <div class="fb-login-button" data-size="medium" data-show-faces="false"
                             data-auto-logout-link="true"></div>
                        <div id="facebookLogin">
                        </div>
                        <h3></h3>
                    </div>
                </div>
                <div class="tab-pane" id="signUp">
                    <h3>Sign up</h3>
                    <div class="forms">
                        <?php echo $this->signUpForm; ?>
                    </div>
                </div>
                <div class="tab-pane" id="about">
                    <h3>About</h3>
                    <p>
                        Universe is a Web Portal application. Designed to get your Mails, News,
                        Social Media, Weather Reporting, Maps and more.<br>All in one place.
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h1>Hi! <?php echo $this->firstName; ?> Great to see You.</h1>
        </div>
        <div class="col-md-8">
            <?php echo $this->webSearchForm; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div id="gMailWidget" class="widgets">
                <div id="gMailHeader">
                    <h2>GMail</h2>
                    <label>
                        <?php
                        echo "<a href='" . $this->baseUrl() . "/index/gmail-refresh'>
                        <span class='fa fa-refresh'></span></a>";
                        ?>
                    </label>
                </div>
                <div id="gMailBody">
                    <?php echo $this->gmailData; ?>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div id="facebookWidget" class="widgets">
                <div id="facebookHeader">
                    <h2>Facebook</h2>
                    <label>
                        <?php
                        echo "<a href='" . $this->baseUrl() . "/index/facebook-refresh'>
                        <span class='fa fa-refresh'></span></a>";
                        ?>
                    </label>
                </div>
                <div id="facebookBody">
                    <?php echo $this->facebookData; ?>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div id="twitterWidget" class="widgets">
                <div id="twitterHeader">
                    <h2>Twitter</h2>
                    <label>
                    <?php
                    echo "<a href='" . $this->baseUrl() . "/index/twitter-refresh'>
                        <span class='fa fa-refresh'></span></a>";
                    ?>
                    </label>
                </div>
                <div id="twitterBody">
                    <?php echo $this->twitterData; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
        </div>
        <div class="col-md-6">
            <div id="googleMapWidget" class="landscapeWidgets">
                <div id="googleMapHeader">
                    <h2>Google Map</h2>
                    <input id="pac-input" class="controls" type="text" placeholder="Search Box">
                </div>
                <div id="googleMap">
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div id="weatherWidget" class="landscapeWidgets">
                <div id="weatherHeader">
                    <h2>Weather</h2>
                    <label>
                        <?php
                        echo "<a href='" . $this->baseUrl() . "/index/twitter-refresh'>
                        <span class='fa fa-refresh'></span></a>";
                        ?>
                    </label>
                </div>
                <div id="weatherBody">
                    <div id="weather">
                        <ul id="scroller">
                            <!-- The forecast items will go here -->
                        </ul>
                        <a href="#" class="arrow previous">Previous</a>
                        <a href="#" class="arrow next">Next</a>
                        <p class="location"></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
