<div id="wrapper">
    <?php if(isset($this->message)) :?>
        <div class="notification">

            <?php echo $this->message ;?>

        </div>
    <?php endif;?>
    <div id="sidebar-wrapper">
        <div class="sidebar-nav nav" id="sidebar-nav">
            <ul id="sidebar-icons">
                <li><a href="#signIn" data-toggle="tab"><span class="menu-open fa fa-sign-in"></span></a></li>
                <li><a href="#signUp" data-toggle="tab"><span class="menu-open fa fa-user"></span></a></li>
                <li><a href="#" data-toggle="tab"><span class="fa fa-cogs"></span></a></li>
                <li><a href="#about" data-toggle="tab"><span class="menu-open fa fa-info-circle"></span></a></li>
                <li><a href="#" id="menu-close" data-toggle="tab"><span class="fa fa-close"></span></a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane" id="signIn">
                    <h3>Sign in</h3>
                    <?php echo $this->signinForm; ?>
                </div>
                <div class="tab-pane" id="signUp">
                    <h3>Sign up</h3>
                    <?php echo $this->signupForm; ?>
                </div>
                <div class="tab-pane" id="about">
                    <h3>About</h3>
                </div>
            </div>
        </div>
    </div>
    <h1>Hi! Great to see You.</h1>
</div>
