<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' | ');
$this->headTitle('Universe');
echo $this->doctype('HTML5') . "\n"; ?>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-signin-client_id" content="955613673981-fpdqjatkpft248qod3ddnin03tmcp9o1.apps.googleusercontent.com">

    <?php echo $this->headMeta() . "\n"; ?>
    <?php echo $this->headTitle() . "\n"; ?>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

    <?php
    $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css');
    echo $this->headLink();
    ?>
</head>
<body>
<div id="content" class="container-fluid">
    <?php echo '<br>' . $this->layout()->content . "\n"; ?>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.0.0/moment.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="https://apis.google.com/js/platform.js" async defer></script>

<?php
$this->headScript()->prependFile($this->baseUrl().'/js/universe.js');
$this->headScript()->prependFile($this->baseUrl().'/js/gmail.js');
$this->headScript()->prependFile($this->baseUrl().'/js/youtube.js');
$this->headScript()->prependFile($this->baseUrl().'/js/weather.js');
$this->headScript()->prependFile($this->baseUrl().'/js/facebookLogin.js');
echo $this->headScript();
?>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD2_nACBJzzxF6AXHzXxcJvYYDTcORZZiA&callback=initMap&libraries=places" async defer></script>
<!--Gmail-->
<script src="https://apis.google.com/js/client.js?onload=handleClientLoad"></script>
<!--youtube-->
<script src="https://apis.google.com/js/client.js?onload=init"></script>
</body>
</html>
